### ISSUE TITLE
Data paging buttons on Table Sort/Filter

### ISSUE THREAD

**Issue by lhsego** [tesseradata/trelliscope#93]
The data paging buttons:
![image](https://cloud.githubusercontent.com/assets/5566573/7123073/639a11f4-e1d4-11e4-8982-bfac7781de6d.png)
would be much more intuitive if they were oriented vertically, either to the left or right of the columns of cognostics.

**Comment by hafen** [comment]
Hmm... it would be difficult to vertically orient because think of large numbers of results to page through - it gets really wide.  Also, unless I'm misinterpreting what you mean, this kind of layout is standard.  For example, see https://www.datatables.net - a very widely used javascript plugin for showing tables in web pages.
